### ISSUE TITLE
Perhaps Dataset member variables should not be private?

### ISSUE THREAD

**Issue by neubig** [ExpressAI/DataLab#120]
Currently many member variables in the `Dataset` class are declared as private using the python convention of starting with `_`. For example, this includes `_stat` and `_info`.

However, it seems from the usage in ExplainaBoard that these should perhaps be accessible to external libraries? Example below:
https://github.com/neulab/ExplainaBoard/blob/main/explainaboard/builders/named_entity_recognition.py#L234

Should these variables be renamed to be public, such as `stat` and `info`? Alternatively, accessor functions could be added as well, but that seems like it might be a bit of overkill.

**Comment by pfliu-nlp** [comment]
Sounds good marked it!
