### ISSUE TITLE
How to get textual labels in `load_dataset`?

### ISSUE THREAD

**Issue by neubig** [ExpressAI/DataLab#153]
Hi! DataLab stores label IDs for text classification tasks as integers. For example see below:

    >>> import datalabs
    >>> from datalabs import load_dataset
    >>> data_values = list(load_dataset(path='sst2', split='test'))
    WARNING:datalabs.builder:Using custom data configuration default
    WARNING:datalabs.builder:Reusing dataset sst2 (/Users/gneubig/.cache/expressai/datalab/sst2/default/0.0.0/1cf5288b3b6fc8d192117283354266dc38a728c596c5910cda7ead9b0e3ab075)
    >>> print(data_values[0])
    {'text': 'if you sometimes like to go to the movies to have fun , wasabi is a good place to start .', 'label': 0}

However, the canonical labels for the dataset are actually textual. For example, if I open the `dataset_info.json` file for this dataset, I was able to see that it has an entry `"labels": ["positive", "negative"]}]`. However, I'm not sure how to get access to the info in the `dataset_info.json` file programmatically. Is there an easy way to do this?

Also, in the longer term it might be nice to have an option to return the labels in text format (perhaps even on by default?). It seems like this would be a thing that many users might want.

**Comment by pfliu-nlp** [comment]
>"However, I'm not sure how to get access to the info in the dataset_info.json file programmatically. Is there an easy way to do this?"

Hey, Graham, this is indeed a little hidden, we usually can obtain it by:

```
from datalabs import load_dataset
test_set = load_dataset(path='sst2', split='test')
text_labels = test_set._info.features['label'].names # text_labels should correspond the label index accordingly
```

>"in the longer term it might be nice to have an option to return the labels in text format (perhaps even on by default?"

this is a good question, we will see if there is something other convenient that the int-style label (e.g., 0, 1, 2) could bring.

**Comment by neubig** [comment]
For reference, I implemented this in ExplainaBoard here:
https://github.com/neulab/ExplainaBoard/pull/233/files#diff-5e2248b7d70eac7963b023b52cf898409feba64e682db4a6ec8c679fff723ddaR274

I think this code could probably be moved to DataLab, but I'm not sure where the best place to put it would be.
