### ISSUE TITLE
load errors: metaphor_qa

### ISSUE THREAD

**Issue by pfliu-nlp** [ExpressAI/DataLab#157]
` File "/usr2/home/pliu3/.cache/expressai/modules/datasets_modules/datalab/metaphor_qa/e0dee7497cfdcd93b6dcb44793c895ef2c136dab08d45bb32082757e993a47d7/metaphor_qa.py", line 166, in _generate_examples
    option_index = int(data[3])
ValueError: invalid literal for int() with base 10: 'The girl was very stable.'`

**Comment by neubig** [comment]
Sorry, there was an error in the dataset format that I was resolving with Emmy, but it's done now. Could you clear your cache and try again?

**Comment by neubig** [comment]
Should be fixed.
