### ISSUE TITLE
Add text classification task?

### ISSUE THREAD

**Issue by pfliu-nlp** [ExpressAI/DataLab#21]
## Sentiment/Topic
* https://drive.google.com/drive/folders/10-cAYSzPxKdzYfZyCZZ8OqyHb8EFuan_?usp=sharing

Dataset description: https://arxiv.org/pdf/1705.04153.pdf

## Aspect-based sentiment classification 
*  https://drive.google.com/drive/u/6/folders/1JttBMEoUmVZ8wF7Qa6C8h32XJpqEOd7u

Note: we need to define new task template for aspect-based sentiment classification [here](https://github.com/ExpressAI/DataLab/tree/main/src/datalabs/tasks)

Dataset Description: https://arxiv.org/pdf/1605.05101.pdf

**Comment by yyy-Apple** [comment]
- [ ] ATIS
- [ ] CR
- [ ] MR
- [ ] QC
- [ ] SST1
- [ ] SST2
- [ ] SUBJ
