### ISSUE TITLE
datasets with `cloze-generative` can not been found (in dev and product explainaboard web)

### ISSUE THREAD

**Issue by pfliu-nlp** [ExpressAI/DataLab#271]
it should be because the new `dataset_info.jsonl` has been overwritten by the old version:
https://github.com/ExpressAI/DataLab/commit/4697a63e83da631b470e74035e8e2b6b47ffe24b#diff-614f8620968a16d2a2fedff6f5ad2cef6dc5af2f192234fe862d890c994008dcL126

@neubig  I guess you probably need to upgrade the datalabs version of your local server.

**Comment by neubig** [comment]
Sorry, that was not because my datalab was outdated, but because I was using the `--previous_json` option to speed up processing, which caches the previous result. But I'll pay attention to this in the future.
