### ISSUE TITLE
add machine translation task?

### ISSUE THREAD

**Issue by pfliu-nlp** [ExpressAI/DataLab#4]
- [ ] define task schema for machine translation
- [ ] add machine translation dataset, supporting WMT?

**Comment by neubig** [comment]
Hey @pfliu-nlp: I'd be interested in getting the WMT and IWSLT datasets added. I'm not sure if I have the bandwidth to do this just yet, but I might sometime in the future. In the meantime if people are actively adding datasets to DataLab this is one that I'd appreciate!

**Comment by pfliu-nlp** [comment]
Aha, ok, let's aim to have these datasets at the end of this week.

**Comment by neubig** [comment]
Done.
